### PR TITLE
Minor typos and changes

### PR DESCRIPTION
**Pull request by xymbol**
Not sure what is the best way to contribute these.

### CODE REVIEW

**Comment by xymbol** [comment]
@abuiles My bad, do you prefer issues instead?

**Comment by abuiles** [comment]
@xymbol no worries :), I'll go through it, I'm right now editing a bunch of stuff to get rid of mentions to Object and Array controller.

**Comment by abuiles** [comment]
@xymbol thanks! finally had the time to go through all  of it.

**Comment by xymbol** [comment]
:+1:

**Pull request closed without merging**
